service_name: qsense-config
release_name: QSense Config

images:
  - name: quickquack/qsense-config

ecr:
  images:
    - ecr_repository: qqcw/qsense-config
      from: quickquack/qsense-config

tests:
  go:
    version: "1.25"
    dirs: [server]
  node:
    dir: client
    node_version: "22"
