name: Build ECR (dev)

on:
  push:
    tags:
      - 'v*-*'

jobs:
  ecr:
    uses: qqcw/gh-actions/.github/workflows/ecr-build.yml@v1
    secrets:
      GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
